export const PARAGRAPH_MIN_LENGTH = 120;
export const PARAGRAPH_MAX_LENGTH = 2500;
export const HIGH_SCORE_STORAGE_KEY = 'hpOracle_hs';
export const BOOK_FEEDBACK_DELAY_MS = 900;
export const WRONG_BOOK_FEEDBACK_DELAY_MS = 1800;
export const CORRECT_CHAPTER_FEEDBACK_DELAY_MS = 1200;
export const INCORRECT_CHAPTER_FEEDBACK_DELAY_MS = 2200;
export const LOADING_SCREEN_DELAY_MS = 350;
